// <auto-generated />
using System;
using Interdisciplinar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab_Protese.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Interdisciplinar.Models.Coleta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("EntregadorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<string>("PedidoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EntregadorId");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Coletas");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Dentista", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dentistas");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Entrega", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("EntregadorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<string>("PedidoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EntregadorId");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Entregador", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entregadores");
                });

            modelBuilder.Entity("Interdisciplinar.Models.ItemPedido", b =>
                {
                    b.Property<string>("PedidoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ServicoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PedidoId", "ServicoId");

                    b.HasIndex("ServicoId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Pedido", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("DentistaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProteticoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DentistaId");

                    b.HasIndex("ProteticoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Protetico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proteticos");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Servico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Coleta", b =>
                {
                    b.HasOne("Interdisciplinar.Models.Entregador", "Entregador")
                        .WithMany("Coletas")
                        .HasForeignKey("EntregadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interdisciplinar.Models.Pedido", "Pedido")
                        .WithOne("Coleta")
                        .HasForeignKey("Interdisciplinar.Models.Coleta", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entregador");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Entrega", b =>
                {
                    b.HasOne("Interdisciplinar.Models.Entregador", "Entregador")
                        .WithMany("Entregas")
                        .HasForeignKey("EntregadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interdisciplinar.Models.Pedido", "Pedido")
                        .WithOne("Entrega")
                        .HasForeignKey("Interdisciplinar.Models.Entrega", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entregador");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Interdisciplinar.Models.ItemPedido", b =>
                {
                    b.HasOne("Interdisciplinar.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interdisciplinar.Models.Servico", "Servico")
                        .WithMany("ItensPedido")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Pedido", b =>
                {
                    b.HasOne("Interdisciplinar.Models.Dentista", "Dentista")
                        .WithMany("Pedidos")
                        .HasForeignKey("DentistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interdisciplinar.Models.Protetico", "Protetico")
                        .WithMany("Pedidos")
                        .HasForeignKey("ProteticoId");

                    b.Navigation("Dentista");

                    b.Navigation("Protetico");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Dentista", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Entregador", b =>
                {
                    b.Navigation("Coletas");

                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Pedido", b =>
                {
                    b.Navigation("Coleta");

                    b.Navigation("Entrega");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Protetico", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Interdisciplinar.Models.Servico", b =>
                {
                    b.Navigation("ItensPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
